# Generated by Django 4.0 on 2022-01-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newslettersubscription_pressreleasesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_credits',
            field=models.IntegerField(default=10),
        ),
    ]
