# Generated by Django 4.0 on 2022-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pressreleasesubmission_company_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
