# Generated by Django 3.2.5 on 2022-01-28 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_admin_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='pressreleasesubmission',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_approved',
            field=models.BooleanField(default=False, verbose_name='Admin approved for Beta use'),
        ),
    ]
