# Generated by Django 3.2.5 on 2022-05-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220129_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressreleasesubmission',
            old_name='company_descriptions',
            new_name='iot',
        ),
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='details',
        ),
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='pressreleasesubmission',
            name='title',
        ),
    ]
